const express = require("express");
const router = express.Router();
const authcontrollers = require('../controllers/auth-controller');
const {signupSchema,loginSchema} = require("../validators/auth-validator");
const validate = require("../middlewares/validate-middleware");
const authMiddleware = require("../middlewares/auth-middleware");
router.get("/",authcontrollers.home);
// router.post("/register",authcontrollers.register);
router.route("/register").post(validate(signupSchema),authcontrollers.register);
router.route("/login").post(validate(loginSchema),authcontrollers.login);
router.route("/user").get(authMiddleware,authcontrollers.user);
module.exports=router;